@UrlShortenerApi_HostAddress = http://localhost:5070

### Encurtar URL aleatória (7 caracteres)
POST {{UrlShortenerApi_HostAddress}}/shorten
Content-Type: application/json

{
  "url": "https://www.google.com"
}

### Encurtar URL com Custom Slug
POST {{UrlShortenerApi_HostAddress}}/shorten
Content-Type: application/json

{
  "url": "https://github.com",
  "customSlug": "meu-github"
}

### Tentar cadastrar o mesmo Custom Slug (deve retornar 409 Conflict)
POST {{UrlShortenerApi_HostAddress}}/shorten
Content-Type: application/json

{
  "url": "https://github.com/outro",
  "customSlug": "meu-github"
}

### Tentar cadastrar com Slug reservado (deve retornar 400 Bad Request)
POST {{UrlShortenerApi_HostAddress}}/shorten
Content-Type: application/json

{
  "url": "https://github.com",
  "customSlug": "swagger"
}

### Redirecionar para URL original (302 Found)
GET {{UrlShortenerApi_HostAddress}}/meu-github
